<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="2" minorVersionNumber="3" buildNumber="8022" updateStamp="_KGQO0XO7EfC3_-SDYT38LQ" externalChecksum="2722078124:507989954" studioType="Javascript" customDataTypeDisplayCount="23">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="51" eDataType="#//state">
        <dataTypeName manuallyCreated="true" value="state"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Alabama'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Arkansas'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Colorado'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'District of Columbia'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Georgia'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hawaii'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Idaho'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Illinois'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Indiana'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Kansas'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Kentucky'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Louisiana'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Maine'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Maryland'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Massachusetts'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Michigan'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Minnesota'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Mississippi'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Missouri'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Montana'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Nebraska'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Nevada'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'New Hampshire'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'New York'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'North Dakota'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Ohio'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Oklahoma'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Oregon'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Pennsylvania'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Rhode Island'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'South Carolina'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'South Dakota'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Texas'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Utah'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Vermont'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Virginia'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Washington'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'West Virginia'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Florida'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Delaware'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Iowa'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Wisconsin'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Arizona'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'California'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'New Jersey'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Tennessee'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'New Mexico'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Wyoming'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Connecticut'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'North Carolina'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Alaska'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="49" eDataType="#//scopeOfCare">
        <dataTypeName manuallyCreated="true" value="scopeOfCare"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Categorically Needy (CN)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medically Needy (MN)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medical Care Services (MCS)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Health Expansion'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//serviceCategory">
        <dataTypeName manuallyCreated="true" value="serviceCategory"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Ambulance (ground and air)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Applied behavior analysis (ABA)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Behavioral health services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Blood/blood products/related services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Dental services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Diagnostic services (lab and X-ray)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Early Periodic Screening, Diagnosis, and Treatment (EPSDT) services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Enteral nutrition program'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Habilitative services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Health care professional services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Health homes'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hearing evaluations'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hearing aids'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Home health services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Home infusion therapy/parenteral nutrition program'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hospice services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hospital services Inpatient/outpatient'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Intermediate care facility/services for persons with intellectual disabilities'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Maternity care and delivery services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medical equipment, supplies, and appliances'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medical nutrition therapy'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Nursing facility services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Organ transplants'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Orthodontic services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Out-of-state services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Outpatient rehabilitation services (OT, PT, ST)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Personal care services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Prescription drugs'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Private duty nursing'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Prosthetic/orthotic devices'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Reproductive health services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Respiratory care (oxygen)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'School-based medical services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Vision care Exams, refractions, and fittings'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Vision hardware Frames and lenses'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//cohort">
        <dataTypeName manuallyCreated="true" value="cohort"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Breast and Cervical Cancer Treatment Program'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medical Care Services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Refugee'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Alien Emergency Medical'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'State-funded long-term care services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'SSI Program'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Workers with Disabilities (HWD'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medically Needy'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medicare Savings Program'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Hospice services'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Long-Term Services and Supports'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="51" eDataType="#//magiPopulations">
        <dataTypeName manuallyCreated="true" value="magiPopulations"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Infants (0-1)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Young Children (Ages 1-5)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Older Children (Ages 6-18)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Higher-Income Children (CHIP)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Pregnant Individuals'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Parents and Caretaker Relatives'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Adult Expansion Group'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Former Foster Care Youth'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Higher-Income Pregnant'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="48" eDataType="#//nonMagiPopulations">
        <dataTypeName manuallyCreated="true" value="nonMagiPopulations"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'ABD'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Supplemental Security Income (SSI) Recipients'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Individuals in Long-Term Care'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Home and Community-Based Services (HCBS) Waiver Recipients'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medically Needy (Spend-down)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Breast and Cervical Cancer Treatment Program Participants'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Katie Beckett'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualified Medicare Beneficiary (QMB)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Specified Low-Income Medicare Beneficiary (SLMB)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualifying Individual (QI)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualified Disabled &amp; Working Individual (QDWI)'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//fundingSource">
        <dataTypeName manuallyCreated="true" value="fundingSource"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medicaid'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'CHIP'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//medicareSavingsPrograms">
        <dataTypeName manuallyCreated="true" value="medicareSavingsPrograms"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualified Medicare Beneficiary (QMB)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualified Disabled &amp; Working Individual (QDWI)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Specified Low-Income Medicare Beneficiary (SLMB)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Qualifying Individual (QI)'"/>
        </enumerationElements>
      </customDataTypeList>
      <vocabularyMappings name="JSON" ID="JSON" mappingType="JSON"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Individual">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Individual"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="livingArrangement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="livingArrangement"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="aged"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="blind"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="disabled"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//state">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="state"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyOrHousehold" lowerBound="1" eType="#//FamilyOrHousehold" eOpposite="#//FamilyOrHousehold/individual">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="familyOrHousehold"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthlyIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="monthlyIncome"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ssn"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="age"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dob" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dob"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usCitizen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="usCitizen"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoMedicaidEligible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="autoMedicaidEligible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chipEligible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="chipEligible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="first"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="last"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pregnant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="pregnant"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isParentOrCaretaker" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isParentOrCaretaker"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTerm" upperBound="-1" eType="#//CoverageTerm" eOpposite="#//CoverageTerm/individual">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverageTerm"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ineligibleDueToImmigrationStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ineligibleDueToImmigrationStatus"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pregnantWithinLast12Months" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="pregnantWithinLast12Months"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ineligibleQHP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ineligibleQHP"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ineligibleFederallyFundedMedicalAssistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ineligibleFederallyFundedMedicalAssistance"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receivesSSI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="receivesSSI"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssiRelated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ssiRelated"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inHospice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="inHospice"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRefugee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isRefugee"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receivesAbdCashAssistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="receivesAbdCashAssistance"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasHCBS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="hasHCBS"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="population" upperBound="-1" eType="#//Population" eOpposite="#//Population/individual">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="population"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medicaidEligible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="medicaidEligible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formerFosterCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="formerFosterCare"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresInstitutionalCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="requiresInstitutionalCare"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inLongTermCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="inLongTermCare"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMedicallyNeedy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isMedicallyNeedy"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participantCancerProgram" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="participantCancerProgram"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highestFavorable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="highestFavorable"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="gender"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="medicareSavingsProgram" eType="#//medicareSavingsPrograms">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.7">
          <name manuallyCreated="true" value="medicareSavingsProgram"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enrolledMedicare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="enrolledMedicare"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hadMedicareUntilReturnToWork" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="hadMedicareUntilReturnToWork"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateRequirement">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="StateRequirement"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presumptiveCHIP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="presumptiveCHIP"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presumptiveMedicaid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="presumptiveMedicaid"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//state">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="state"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyOrHousehold" lowerBound="1" eType="#//FamilyOrHousehold" eOpposite="#//FamilyOrHousehold/stateRequirement">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="familyOrHousehold"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="povertyGuideline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="povertyGuideline"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="householdSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="householdSize"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="population" upperBound="-1" eType="#//Population" eOpposite="#//Population/stateRequirement">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="population"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eligibilityGroups" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="eligibilityGroups"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="state">
    <eLiterals name="V0" literal="'Alabama'"/>
    <eLiterals name="V1" value="1" literal="'Arkansas'"/>
    <eLiterals name="V2" value="2" literal="'Colorado'"/>
    <eLiterals name="V3" value="3" literal="'District of Columbia'"/>
    <eLiterals name="V4" value="4" literal="'Georgia'"/>
    <eLiterals name="V5" value="5" literal="'Hawaii'"/>
    <eLiterals name="V6" value="6" literal="'Idaho'"/>
    <eLiterals name="V7" value="7" literal="'Illinois'"/>
    <eLiterals name="V8" value="8" literal="'Indiana'"/>
    <eLiterals name="V9" value="9" literal="'Kansas'"/>
    <eLiterals name="V10" value="10" literal="'Kentucky'"/>
    <eLiterals name="V11" value="11" literal="'Louisiana'"/>
    <eLiterals name="V12" value="12" literal="'Maine'"/>
    <eLiterals name="V13" value="13" literal="'Maryland'"/>
    <eLiterals name="V14" value="14" literal="'Massachusetts'"/>
    <eLiterals name="V15" value="15" literal="'Michigan'"/>
    <eLiterals name="V16" value="16" literal="'Minnesota'"/>
    <eLiterals name="V17" value="17" literal="'Mississippi'"/>
    <eLiterals name="V18" value="18" literal="'Missouri'"/>
    <eLiterals name="V19" value="19" literal="'Montana'"/>
    <eLiterals name="V20" value="20" literal="'Nebraska'"/>
    <eLiterals name="V21" value="21" literal="'Nevada'"/>
    <eLiterals name="V22" value="22" literal="'New Hampshire'"/>
    <eLiterals name="V23" value="23" literal="'New York'"/>
    <eLiterals name="V24" value="24" literal="'North Dakota'"/>
    <eLiterals name="V25" value="25" literal="'Ohio'"/>
    <eLiterals name="V26" value="26" literal="'Oklahoma'"/>
    <eLiterals name="V27" value="27" literal="'Oregon'"/>
    <eLiterals name="V28" value="28" literal="'Pennsylvania'"/>
    <eLiterals name="V29" value="29" literal="'Rhode Island'"/>
    <eLiterals name="V30" value="30" literal="'South Carolina'"/>
    <eLiterals name="V31" value="31" literal="'South Dakota'"/>
    <eLiterals name="V32" value="32" literal="'Texas'"/>
    <eLiterals name="V33" value="33" literal="'Utah'"/>
    <eLiterals name="V34" value="34" literal="'Vermont'"/>
    <eLiterals name="V35" value="35" literal="'Virginia'"/>
    <eLiterals name="V36" value="36" literal="'Washington'"/>
    <eLiterals name="V37" value="37" literal="'West Virginia'"/>
    <eLiterals name="V38" value="38" literal="'Florida'"/>
    <eLiterals name="V39" value="39" literal="'Delaware'"/>
    <eLiterals name="V40" value="40" literal="'Iowa'"/>
    <eLiterals name="V41" value="41" literal="'Wisconsin'"/>
    <eLiterals name="V42" value="42" literal="'Arizona'"/>
    <eLiterals name="V43" value="43" literal="'California'"/>
    <eLiterals name="V44" value="44" literal="'New Jersey'"/>
    <eLiterals name="V45" value="45" literal="'Tennessee'"/>
    <eLiterals name="V46" value="46" literal="'New Mexico'"/>
    <eLiterals name="V47" value="47" literal="'Wyoming'"/>
    <eLiterals name="V48" value="48" literal="'Connecticut'"/>
    <eLiterals name="V49" value="49" literal="'North Carolina'"/>
    <eLiterals name="V50" value="50" literal="'Alaska'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageTerm">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="CoverageTerm"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="startDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="endDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageProgram" lowerBound="1" upperBound="-1" eType="#//CoverageProgram" eOpposite="#//CoverageProgram/coverageTerm">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverageProgram"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" lowerBound="1" eType="#//Individual" eOpposite="#//Individual/coverageTerm">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="individual"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="population" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="population"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retroactiveToDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="retroactiveToDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyOrHousehold">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="FamilyOrHousehold"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" upperBound="-1" eType="#//Individual" eOpposite="#//Individual/familyOrHousehold">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="individual"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="size"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//state">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="state"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="povertyGuideline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="povertyGuideline"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateRequirement" eType="#//StateRequirement" eOpposite="#//StateRequirement/familyOrHousehold">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="stateRequirement"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthlyIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="monthlyIncome"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="householdPercentFPL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="householdPercentFPL"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annualIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="annualIncome"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="county" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="county"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="householdId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="householdId"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageProgram">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="CoverageProgram"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopeOfCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="scopeOfCare"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1" eType="#//Service" eOpposite="#//Service/coverageProgram">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="service"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTerm" eType="#//CoverageTerm" eOpposite="#//CoverageTerm/coverageProgram">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverageTerm"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cohort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="cohort"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="scopeOfCare">
    <eLiterals name="V0" literal="'Categorically Needy (CN)'"/>
    <eLiterals name="V1" value="1" literal="'Alternative Benefits Plan (ABP)'"/>
    <eLiterals name="V2" value="2" literal="'Medically Needy (MN)'"/>
    <eLiterals name="V3" value="3" literal="'Medical Care Services (MCS)'"/>
    <eLiterals name="V4" value="4" literal="'Health Expansion'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Service"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//serviceCategory">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.2">
          <name manuallyCreated="true" value="category"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageProgram" lowerBound="1" eType="#//CoverageProgram" eOpposite="#//CoverageProgram/service">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverageProgram"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="serviceCategory">
    <eLiterals name="V0" literal="'Ambulance (ground and air)'"/>
    <eLiterals name="V1" value="1" literal="'Applied behavior analysis (ABA)'"/>
    <eLiterals name="V2" value="2" literal="'Behavioral health services'"/>
    <eLiterals name="V3" value="3" literal="'Blood/blood products/related services'"/>
    <eLiterals name="V4" value="4" literal="'Dental services'"/>
    <eLiterals name="V5" value="5" literal="'Diagnostic services (lab and X-ray)'"/>
    <eLiterals name="V6" value="6" literal="'Early Periodic Screening, Diagnosis, and Treatment (EPSDT) services'"/>
    <eLiterals name="V7" value="7" literal="'Enteral nutrition program'"/>
    <eLiterals name="V8" value="8" literal="'Habilitative services'"/>
    <eLiterals name="V9" value="9" literal="'Health care professional services'"/>
    <eLiterals name="V10" value="10" literal="'Health homes'"/>
    <eLiterals name="V11" value="11" literal="'Hearing evaluations'"/>
    <eLiterals name="V12" value="12" literal="'Hearing aids'"/>
    <eLiterals name="V13" value="13" literal="'Home health services'"/>
    <eLiterals name="V14" value="14" literal="'Home infusion therapy/parenteral nutrition program'"/>
    <eLiterals name="V15" value="15" literal="'Hospice services'"/>
    <eLiterals name="V16" value="16" literal="'Hospital services Inpatient/outpatient'"/>
    <eLiterals name="V17" value="17" literal="'Intermediate care facility/services for persons with intellectual disabilities'"/>
    <eLiterals name="V18" value="18" literal="'Maternity care and delivery services'"/>
    <eLiterals name="V19" value="19" literal="'Medical equipment, supplies, and appliances'"/>
    <eLiterals name="V20" value="20" literal="'Medical nutrition therapy'"/>
    <eLiterals name="V21" value="21" literal="'Nursing facility services'"/>
    <eLiterals name="V22" value="22" literal="'Organ transplants'"/>
    <eLiterals name="V23" value="23" literal="'Orthodontic services'"/>
    <eLiterals name="V24" value="24" literal="'Out-of-state services'"/>
    <eLiterals name="V25" value="25" literal="'Outpatient rehabilitation services (OT, PT, ST)'"/>
    <eLiterals name="V26" value="26" literal="'Personal care services'"/>
    <eLiterals name="V27" value="27" literal="'Prescription drugs'"/>
    <eLiterals name="V28" value="28" literal="'Private duty nursing'"/>
    <eLiterals name="V29" value="29" literal="'Prosthetic/orthotic devices'"/>
    <eLiterals name="V30" value="30" literal="'Reproductive health services'"/>
    <eLiterals name="V31" value="31" literal="'Respiratory care (oxygen)'"/>
    <eLiterals name="V32" value="32" literal="'School-based medical services'"/>
    <eLiterals name="V33" value="33" literal="'Vision care Exams, refractions, and fittings'"/>
    <eLiterals name="V34" value="34" literal="'Vision hardware Frames and lenses'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="cohort">
    <eLiterals name="V0" literal="'Breast and Cervical Cancer Treatment Program'"/>
    <eLiterals name="V1" value="1" literal="'Medical Care Services'"/>
    <eLiterals name="V2" value="2" literal="'Refugee'"/>
    <eLiterals name="V3" value="3" literal="'Alien Emergency Medical'"/>
    <eLiterals name="V4" value="4" literal="'State-funded long-term care services'"/>
    <eLiterals name="V5" value="5" literal="'SSI Program'"/>
    <eLiterals name="V6" value="6" literal="'Workers with Disabilities (HWD'"/>
    <eLiterals name="V7" value="7" literal="'Medically Needy'"/>
    <eLiterals name="V8" value="8" literal="'Medicare Savings Program'"/>
    <eLiterals name="V9" value="9" literal="'Hospice services'"/>
    <eLiterals name="V10" value="10" literal="'Long-Term Services and Supports'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Population">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Population"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="group"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magiIncomePercent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="magiIncomePercent"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAssetTest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="hasAssetTest"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetLimitIndividual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="assetLimitIndividual"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetLimitCouple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="assetLimitCouple"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minAge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="minAge"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="maxAge"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" lowerBound="1" eType="#//Individual" eOpposite="#//Individual/population">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="individual"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magiGroup" eType="#//magiPopulations">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.4">
          <name manuallyCreated="true" value="magiGroup"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonMagiGroup" eType="#//nonMagiPopulations">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.5">
          <name manuallyCreated="true" value="nonMagiGroup"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateRequirement" lowerBound="1" eType="#//StateRequirement" eOpposite="#//StateRequirement/population">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="stateRequirement"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fundingSource" eType="#//fundingSource">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.6">
          <name manuallyCreated="true" value="fundingSource"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magiIncomePercentLowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="magiIncomePercentLowerBound"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eligibleForPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="eligibleForPath"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="favorability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="favorability"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incomeIneligible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="incomeIneligible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="magiPopulations">
    <eLiterals name="V0" literal="'Infants (0-1)'"/>
    <eLiterals name="V1" value="1" literal="'Young Children (Ages 1-5)'"/>
    <eLiterals name="V2" value="2" literal="'Older Children (Ages 6-18)'"/>
    <eLiterals name="V3" value="3" literal="'Higher-Income Children (CHIP)'"/>
    <eLiterals name="V4" value="4" literal="'Pregnant Individuals'"/>
    <eLiterals name="V5" value="5" literal="'Parents and Caretaker Relatives'"/>
    <eLiterals name="V6" value="6" literal="'Adult Expansion Group'"/>
    <eLiterals name="V7" value="7" literal="'Former Foster Care Youth'"/>
    <eLiterals name="V8" value="8" literal="'Higher-Income Pregnant'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="nonMagiPopulations">
    <eLiterals name="V0" literal="'ABD'"/>
    <eLiterals name="V1" value="1" literal="'Blind'"/>
    <eLiterals name="V2" value="2" literal="'Disabled'"/>
    <eLiterals name="V3" value="3" literal="'Supplemental Security Income (SSI) Recipients'"/>
    <eLiterals name="V4" value="4" literal="'Individuals in Long-Term Care'"/>
    <eLiterals name="V5" value="5" literal="'Home and Community-Based Services (HCBS) Waiver Recipients'"/>
    <eLiterals name="V6" value="6" literal="'Medically Needy (Spend-down)'"/>
    <eLiterals name="V7" value="7" literal="'Breast and Cervical Cancer Treatment Program Participants'"/>
    <eLiterals name="V8" value="8" literal="'Katie Beckett'"/>
    <eLiterals name="V9" value="9" literal="'Qualified Medicare Beneficiary (QMB)'"/>
    <eLiterals name="V10" value="10" literal="'Specified Low-Income Medicare Beneficiary (SLMB)'"/>
    <eLiterals name="V11" value="11" literal="'Qualifying Individual (QI)'"/>
    <eLiterals name="V12" value="12" literal="'Qualified Disabled &amp; Working Individual (QDWI)'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="fundingSource">
    <eLiterals name="V0" literal="'Medicaid'"/>
    <eLiterals name="V1" value="1" literal="'CHIP'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="medicareSavingsPrograms">
    <eLiterals name="V0" literal="'Qualified Medicare Beneficiary (QMB)'"/>
    <eLiterals name="V1" value="1" literal="'Qualified Disabled &amp; Working Individual (QDWI)'"/>
    <eLiterals name="V2" value="2" literal="'Specified Low-Income Medicare Beneficiary (SLMB)'"/>
    <eLiterals name="V3" value="3" literal="'Qualifying Individual (QI)'"/>
  </eClassifiers>
</ecore:EPackage>
