mlAppName=${APP_NAME}
mlHost=${MARKLOGIC_HOST}
mlUsername=${MARKLOGIC_ADMIN_USERNAME}
mlPassword=${MARKLOGIC_ADMIN_PASSWORD}
mlRestPort=${MARKLOGIC_REST_PORT}

usernameAdmin=${MARKLOGIC_APP_ADMIN_USERNAME}
passwordAdmin=${MARKLOGIC_APP_ADMIN_PASSWORD}
usernameWriter=${MARKLOGIC_APP_WRITER_USERNAME}
passwordWriter=${MARKLOGIC_APP_WRITER_PASSWORD}
usernameReader=${MARKLOGIC_APP_READER_USERNAME}
passwordReader=${MARKLOGIC_APP_READER_PASSWORD}

ml_rest_authentication=${ML_REST_AUTHENTICATION}
collectionPrefix=${COLLECTION_PREFIX}
mlDatabasesWithForestsOnOneHost=${APP_NAME}-modules,${APP_NAME}-schemas,Security
mlContentForestsPerHost=1
